/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A single cell in a worksheet.
 *
 * Holds `Arc<Mutex<CellInner>>` so that every clone shares the same underlying
 * state — value and style mutations made through any handle persist to the
 * worksheet's internal model.
 */
export declare class Cell {
  constructor(address: string, row: number, col: number)
  get value(): CellValue
  /** Returns a JS `Date` for Date-type cells, or `null` otherwise. */
  get date(): Date | null
  /**
   * Accepts JS primitives and CellValue objects.
   *
   * Three-path dispatch:
   * 1. Raw JS `Date` → serial (for `cell.value = new Date(...)`)
   * 2. `CellValue` object / other objects → `Null` (round-trip via object is not supported)
   * 3. `serde_json::Value` fallback (Number, String, Bool, Null)
   */
  set value(val: unknown)
  get address(): string
  get row(): number
  get col(): number
  get formula(): string | null
  /**
   * Convenience getter for the comment text (ExcelJS `cell.note`).
   * Returns `None` when the cell has no comment.
   */
  get note(): string | null
  /**
   * Convenience setter for the comment text (ExcelJS `cell.note = "..."`).
   * Preserves any existing author.
   */
  set note(text: string)
  /** Full comment accessor (text + author). */
  get comment(): CellComment | null
  /** Full comment setter (text + author). */
  set comment(c: CellComment | undefined | null)
  /** Returns the cell's style, or `None` if Normal (index 0). */
  get style(): Style | null
  /**
   * Set the cell's style from a JS object. Full-replace semantics
   * (spec §6.9): assigning a new style replaces the existing one.
   *
   * - `null | undefined | {}` → resets to Normal (None).
   * - Throws `ExcelrsError::InvalidStyle` on validation failure.
   */
  set style(val: Style | null)
}

/**
 * A column definition in a worksheet.
 *
 * Mirrors the exceljs `Column` interface: header label, data-binding key,
 * width in characters, hidden state, and 1-indexed column number.
 *
 * `col_num` is optional in the JS object. If omitted (or 0), it is
 * auto-assigned sequentially in `Worksheet.setColumns` — the first column
 * gets col_num=1, the second gets col_num=2, etc.  For sparse definitions
 * (e.g. defining only column B), pass the `colNum` explicitly.
 */
export declare class Column {
  constructor(header: string, key: string, width: number)
  get header(): string
  set header(val: string)
  get key(): string
  set key(val: string)
  get width(): number
  set width(val: number)
  get hidden(): boolean
  set hidden(val: boolean)
  get style(): Style | null
  set style(val: Style | null)
  get colNum(): number
}

/**
 * A row in a worksheet.
 *
 * Cells are stored in a `HashMap<u32, Cell>` keyed by 1-indexed column number.
 * The row number is 1-indexed. Accessing a cell by column creates an empty cell
 * if one doesn't exist — the returned Cell is a clone (see clone-on-read semantics
 * in `cell.rs`).
 */
export declare class Row {
  constructor(number: number)
  get number(): number
  get height(): number | null
  set height(val: number | undefined | null)
  get hidden(): boolean
  set hidden(val: boolean)
  get style(): Style | null
  set style(val: Style | null)
  /**
   * Get cell by 1-indexed column number. Creates an empty cell if none exists.
   * This is the Rust backing for `Row.getCell(col: number)`.
   */
  getCellByColNum(col: number): Cell
  /**
   * Get cell by column letter. Creates an empty cell if none exists.
   * This is the Rust backing for `Row.getCell(col: string)`.
   */
  getCellByColLetter(colLetter: string): Cell
  /** Get cell by 1-indexed column number (JS glue → getCellByColNum). */
  getCell(col: number): Cell
  /** Get cell by column letter (JS glue → getCellByColLetter). */
  getCell(col: string): Cell
}

/**
 * Top-level workbook document.
 *
 * Wraps `WorkbookInner` behind `Arc<Mutex<>>` so that the `WorkbookXlsx`
 * handle can mutate the workbook state via a shared reference.
 *
 * # Clone-on-read semantics
 * Like all napi-rs model types, accessed worksheets are cloned across the FFI
 * boundary.  Cloning the `Workbook` itself clones the `Arc` — all clones share
 * the same inner state.
 */
export declare class Workbook {
  constructor()
  /**
   * Add a new worksheet with the given name.
   * Returns the created Worksheet.
   */
  addWorksheet(name: string): Worksheet
  /**
   * Get a worksheet by name (string) or 1-indexed position (number).
   * Returns `None` if not found.
   */
  getWorksheet(nameOrIndex: string | number): Worksheet | null
  get worksheets(): Array<Worksheet>
  get worksheetCount(): number
  /** ISO-8601 timestamp of workbook creation. */
  get created(): string
  /** ISO-8601 timestamp of last modification. */
  get modified(): string
  /**
   * Returns a `WorkbookXlsx` handle for async XLSX I/O.
   *
   * The handle shares the same underlying `Arc<Mutex<WorkbookInner>>`,
   * so reads through `.xlsx.read(buf)` mutate this workbook's state.
   */
  get xlsx(): WorkbookXlsx
  /**
   * Returns a `WorkbookCsv` handle for async CSV I/O.
   *
   * The handle shares the same underlying `Arc<Mutex<WorkbookInner>>`
   * as the parent Workbook.
   */
  get csv(): WorkbookCsv
  /** Snapshot of all defined names in the workbook. */
  get definedNames(): Array<DefinedName>
  /**
   * Add or upsert a defined name.
   *
   * Workbook-scope: matched by `name` alone.
   * Sheet-scope: matched by `name` + `sheet`.
   */
  addDefinedName(name: string, value: string, sheet?: string | undefined | null): void
  /**
   * Remove a defined name by `name` (and optional `sheet`).
   * No-op if no matching name exists.
   */
  removeDefinedName(name: string, sheet?: string | undefined | null): void
  /**
   * Get a defined name by `name` (and optional `sheet`).
   * Returns `None` if not found.
   */
  getDefinedName(name: string, sheet?: string | undefined | null): DefinedName | null
  get views(): Array<WorkbookView>
  set views(views: Array<WorkbookView>)
  get calcProperties(): CalcProperties | null
  set calcProperties(calc: CalcProperties | undefined | null)
}

/**
 * Async CSV read/write handle.
 *
 * Obtained via `Workbook.csv` getter.  Shares the same underlying
 * `Arc<Mutex<WorkbookInner>>` as the parent Workbook.
 */
export declare class WorkbookCsv {
  /**
   * Parse a CSV `Buffer` into a single worksheet ("Sheet1"), replacing
   * the workbook's existing worksheets in place.
   *
   * An optional `delimiter` overrides the field separator (default `,`).
   */
  read(buffer: Buffer, delimiter?: string | undefined | null): Promise<void>
  /**
   * Read a CSV file from disk into a single worksheet ("Sheet1").
   *
   * An optional `delimiter` overrides the field separator (default `,`).
   */
  readFile(path: string, delimiter?: string | undefined | null): Promise<void>
  /**
   * Serialize the first worksheet to a CSV `Buffer`.
   *
   * Optional `delimiter` (default `,`) and `withBom` (default `false`).
   * Only `worksheets[0]` is written (CSV is single-sheet).
   */
  write(delimiter?: string | undefined | null, withBom?: boolean | undefined | null): Promise<Buffer>
  /**
   * Serialize the first worksheet to a CSV file on disk.
   *
   * Optional `delimiter` (default `,`) and `withBom` (default `false`).
   */
  writeFile(path: string, delimiter?: string | undefined | null, withBom?: boolean | undefined | null): Promise<void>
}

/**
 * Async XLSX read/write handle.
 *
 * Obtained via `Workbook.xlsx` getter.  Shares the same underlying
 * `Arc<Mutex<WorkbookInner>>` as the parent Workbook.
 */
export declare class WorkbookXlsx {
  /**
   * Read an .xlsx file from a JS `Buffer`.  Async.
   *
   * Parses the buffer with calamine, then replaces the workbook state
   * in-place.  All existing worksheets are discarded.
   *
   * @remarks Must be awaited.  The workbook state is only swapped when the
   * returned Promise resolves.  Accessing worksheets before awaiting the
   * Promise will see the old (stale) state.
   */
  read(buffer: Buffer): Promise<void>
  /**
   * Read an .xlsx file from disk.  Async.
   *
   * @remarks Must be awaited.  The workbook state is only swapped when the
   * returned Promise resolves.  Accessing worksheets before awaiting the
   * Promise will see the old (stale) state.
   */
  readFile(path: string): Promise<void>
  /**
   * Write the workbook to an .xlsx buffer.  Async.
   *
   * Clones the workbook state briefly under the lock, then builds the
   * .xlsx archive outside the lock (calamine / zip I/O is expensive).
   *
   * @remarks Must be awaited.  The returned Promise resolves to a Buffer
   * of the .xlsx data.
   */
  write(): Promise<Buffer>
  /**
   * Write the workbook to an .xlsx file on disk.  Async.
   *
   * @remarks Must be awaited.  The file is only fully written when the
   * returned Promise resolves.
   */
  writeFile(path: string): Promise<void>
}

/**
 * A single worksheet (sheet) in a workbook.
 *
 * Rows are stored behind `Arc<Mutex<>>` so that any clone of a Worksheet
 * shares the same row state.  This is what makes `wb.addWorksheet() → ws`
 * → `ws.addRow(...)` work across the napi-rs FFI boundary.
 */
export declare class Worksheet {
  constructor(name: string)
  get name(): string
  set name(val: string)
  get id(): number
  /** Number of rows with content (highest row index with data). */
  get rowCount(): number
  /** Number of columns with content (highest column index across all rows). */
  get columnCount(): number
  /**
   * Get cell by A1-style address string (e.g., "A1", "BC42").
   * Returns an empty cell if the address is valid but hasn't been populated.
   */
  getCellByAddress(address: string): Cell
  /**
   * Get cell by 1-indexed row and column numbers.
   * Returns the cell from the worksheet's internal row map, so value and style
   * mutations on the returned cell persist into the worksheet.
   * Creates the row (and cell) if absent.
   */
  getCellByRc(row: number, col: number): Cell
  /** Get cell by A1-style address string (JS glue → getCellByAddress). */
  getCell(address: string): Cell
  /** Get cell by 1-indexed row and column numbers (JS glue → getCellByRc). */
  getCell(row: number, col: number): Cell
  /** Get row by 1-indexed row number. Creates the row if it doesn't exist. */
  getRow(rowNumber: number): Row
  /** Add a row of cell values. Returns the created Row. */
  addRow(values: Array<CellValue | number | string | boolean | null>): Row
  /**
   * Get a contiguous range of rows starting at `start` (1-indexed).
   * Returns up to `count` rows.
   */
  getRows(start: number, count: number): Array<Row>
  /** Remove a row by number. No-op if the row doesn't exist. */
  removeRow(rowNumber: number): void
  /** All rows with content, sorted by row number. */
  get rows(): Array<Row>
  get columns(): Array<Column>
  /**
   * Set the style of a cell at (row, col).  Bypasses clone-on-read:
   * the cell is mutated inside the locked row map.
   */
  setCellStyle(row: number, col: number, style: Style | null): void
  /**
   * Replace the worksheet's column definitions.
   *
   * Accepts a JS array of column descriptor objects (header, key, width,
   * optional hidden, optional style). Parsed server-side via serde.
   * Each column's style is validated (matching `Cell.set_style` behavior).
   * Replace the worksheet's column definitions.
   *
   * Accepts a JS array of column descriptor objects (header, key, width,
   * optional `colNum`, optional hidden, optional style).  Parsed
   * server-side via serde.  Each column's style is validated (matching
   * `Cell.set_style` behavior).
   *
   * `colNum` auto-assignment: columns with `colNum == 0` get sequential
   * numbers starting from `max(existing col_nums) + 1` (or 1 if none
   * exist).  Duplicate `colNum` values across the same call are rejected.
   */
  setColumns(cols: Array<ColumnInput>): void
  /**
   * Merge a range of cells (e.g. "A1:C3"). Accepts an A1-style range string.
   * Validates that the range parses to a rectangular area; stores it for
   * emission in the writer. Duplicate ranges are silently ignored.
   */
  mergeCells(range: string): void
  /** Get all data validations for this worksheet. */
  get dataValidations(): Array<DataValidation>
  /** Add or update a data validation. Upserts by sqref. */
  addDataValidation(dv: DataValidation): void
  /** Get data validation for a specific cell reference (sqref). */
  getDataValidation(sqref: string): DataValidation | null
  /** Get the worksheet's auto-filter range (e.g. "A1:C1"). Returns `None` if unset. */
  get autoFilter(): string | null
  /** Set the worksheet's auto-filter range. Pass `null` or `""` to clear. */
  set autoFilter(val: string | undefined | null)
  /** Get the worksheet's view descriptors (freeze/split panes). */
  get views(): Array<SheetView>
  /** Set the worksheet's view descriptors. */
  set views(val: Array<SheetView>)
  /** Get the worksheet's protection flags. Returns `None` if unprotected. */
  get protection(): SheetProtection | null
  /** Set the worksheet's protection flags. Pass `null` to clear. */
  set protection(val: SheetProtection | undefined | null)
  /** Get the worksheet's header/footer descriptor. Returns `None` if unset. */
  get headerFooter(): HeaderFooter | null
  /** Set the worksheet's header/footer descriptor. Pass `null` to clear. */
  set headerFooter(val: HeaderFooter | undefined | null)
  /** Get the worksheet's page setup / print descriptor. Returns `None` if unset. */
  get pageSetup(): PageSetup | null
  /** Set the worksheet's page setup / print descriptor. Pass `null` to clear. */
  set pageSetup(val: PageSetup | undefined | null)
  /** Remove data validation for a specific cell reference (sqref). */
  removeDataValidation(sqref: string): boolean
  /** Add an embedded image to the worksheet. Returns the image index. */
  addImage(opts: AddImageOptions): number
  /** Return all embedded images on the worksheet. */
  getImages(): Array<ImageInfo>
  /**
   * Add a structured table to the worksheet (ExcelJS `ws.addTable`).
   *
   * Writes the header row (from `columns` names), the data rows, and the
   * optional totals row into the referenced cells, then registers the table
   * model. Returns the created `Table`.
   */
  addTable(opts: AddTableOptions): Table
  /** Return the table with the given name, or `null` if not found. */
  getTable(name: string): Table | null
  /** Return all tables on the worksheet. */
  getTables(): Array<Table>
  /** Remove the named table (and its part/relationship); cells stay intact. */
  removeTable(name: string): boolean
}

export interface AddImageOptions {
  extension: string
  buffer: Array<number>
  imageType?: string
  positioning?: string
  anchor: ImageAnchor
}

/** Cell content alignment and text wrapping. */
export interface Alignment {
  /** Horizontal: `"left"` | `"center"` | `"right"` | `"fill"` | `"justify"`. */
  horizontal?: string
  /** Vertical: `"top"` | `"middle"` | `"bottom"`. */
  vertical?: string
  wrapText?: boolean
  indent?: number
}

/** All cell-border sides plus diagonals. Each side is optional; `None` means no border. */
export interface Border {
  top?: BorderStyle
  right?: BorderStyle
  bottom?: BorderStyle
  left?: BorderStyle
  /** Diagonal border line style. Only valid edges between top-left ↔ bottom-right. */
  diagonal?: BorderStyle
  /**
   * Whether the diagonal line goes up (bottom-left to top-right).
   * OOXML attribute `diagonalUp` on the `<border>` element.
   */
  diagonalUp?: boolean
  /**
   * Whether the diagonal line goes down (top-left to bottom-right).
   * OOXML attribute `diagonalDown` on the `<border>` element.
   */
  diagonalDown?: boolean
}

/** Border line style and color for one side of a cell border. */
export interface BorderStyle {
  /**
   * Border style: `"thin"` | `"medium"` | `"thick"` | `"dashed"` |
   * `"dotted"` | `"double"`. `"none"` is rejected; use `None` for
   * the border side (e.g. `Border.top = None`) to express no border.
   */
  style: string
  /** Line color (ARGB hex). Default: black (`"FF000000"` in exceljs). */
  color?: string
}

/** Workbook calculation properties (`CT_CalcPr`). */
export interface CalcProperties {
  fullCalcOnLoad?: boolean
  calcId?: number
  calcMode?: string
  refFullCalc?: boolean
  iterate?: boolean
  iterateCount?: number
  iterateDelta?: number
}

/** A cell comment (note). `text` is the comment body; `author` is optional. */
export interface CellComment {
  text: string
  author?: string
}

export interface CellValue {
  /**
   * Discriminant: "Null" | "Number" | "String" | "Boolean" | "Formula" | "Error"
   * | "Hyperlink" | "RichText" | "Merge"
   */
  valueType: string
  number?: number
  string?: string
  boolean?: boolean
  formula?: string
  errorValue?: string
  /** URL for hyperlink (write-only, Null on read). */
  hyperlink?: string
  /** Display text for hyperlink (write-only, Null on read). */
  hyperlinkText?: string
  /** Rich text runs (write-only, Null on read). */
  richText?: Array<RichTextRun>
  /**
   * Excel serial date value (days since 1899-12-30; fractional part = time of day).
   * Exposed as `dateSerial` on the JS `CellValue` object for round-trip support.
   */
  dateSerial?: number
}

/** Data validation constraint on a cell range. */
export interface DataValidation {
  /** Cell range reference (e.g. "A1", "A1:B10", "A1 C1:D5"). */
  sqref: string
  /** Validation type: "whole", "decimal", "list", "date", "time", "textLength", "custom". */
  type: string
  /**
   * Operator for range-based types: "between", "notBetween", "equal", "notEqual",
   * "greaterThan", "lessThan", "greaterThanOrEqual", "lessThanOrEqual".
   * Only used with "whole", "decimal", "date", "time", "textLength".
   */
  operator?: string
  /** First formula value (constraint lower bound, or single value, or list). */
  formula1: string
  /** Second formula value (constraint upper bound); only used with "between"/"notBetween". */
  formula2?: string
  /** Allow blank cells (default: true). When true, cells in sqref can be empty. */
  allowBlank?: boolean
  /** Show input prompt message (default: false). */
  showInputMessage?: boolean
  /** Show error message (default: false). */
  showErrorMessage?: boolean
  /** Input prompt text. */
  prompt?: string
  /** Input prompt title. */
  promptTitle?: string
  /** Error message text. */
  error?: string
  /** Error message title. */
  errorTitle?: string
  /** Error message type: "information", "warning", "stop". */
  errorStyle?: string
}

/**
 * A named range or defined name in the workbook.
 *
 * - `name`: The defined name identifier (e.g. `"TaxRate"`, `"MyRange"`).
 * - `value`: The raw OOXML text content (e.g. `"Sheet1!$A$1"`, `"0.08"`).
 * - `sheet`: For sheet-scoped names (`localSheetId` resolved on read), the
 *   resolved sheet name.  `None` for workbook-global names.
 */
export interface DefinedName {
  name: string
  value: string
  sheet?: string
}

/** Cell fill: kind, foreground, background, and pattern. */
export interface Fill {
  /** Fill kind: `"none"` | `"solid"` | `"pattern"` | `"gradient"`. */
  kind: string
  /** Foreground color (ARGB hex). Default: None. */
  foreground?: string
  /** Background color (ARGB hex). Default: None. */
  background?: string
  /** Pattern name (for `kind="pattern"`). Default: None. */
  pattern?: string
  /** Gradient type: `"linear"` or `"path"`. Only used when `kind="gradient"`. */
  gradientType?: string
  /** Gradient angle in degrees (linear). Only used when `kind="gradient"`. */
  gradientDegree?: number
  /** Gradient angle as left/right angle (for path gradients). Only used when `kind="gradient"`. */
  gradientAngle?: number
  /** Gradient stops. Only used when `kind="gradient"`. */
  gradientStops?: Array<GradientStop>
  /** Left edge position (0.0–1.0) for path gradients. Only used when `kind="gradient"` and `gradient_type="path"`. */
  gradientLeft?: number
  /** Right edge position (0.0–1.0) for path gradients. Only used when `kind="gradient"` and `gradient_type="path"`. */
  gradientRight?: number
  /** Top edge position (0.0–1.0) for path gradients. Only used when `kind="gradient"` and `gradient_type="path"`. */
  gradientTop?: number
  /** Bottom edge position (0.0–1.0) for path gradients. Only used when `kind="gradient"` and `gradient_type="path"`. */
  gradientBottom?: number
}

/** Font properties: name, size (points), weight, style, and color. */
export interface Font {
  /** Font name (e.g. "Calibri", "Arial"). Default: "Calibri". */
  name?: string
  /** Font size in points. Default: 11. Must be finite. */
  size?: number
  bold?: boolean
  italic?: boolean
  underline?: boolean
  /** ARGB hex (8 chars) or RGB hex (6 chars). Default: None. */
  color?: string
}

/** A single gradient stop: color + position. */
export interface GradientStop {
  /** ARGB hex color (8 chars) or RGB hex (6 chars). */
  color: string
  /** Position in [0.0, 1.0]. */
  position: number
}

/** Header/footer descriptor for a worksheet (mirrors ExcelJS `ws.headerFooter`). */
export interface HeaderFooter {
  /** Left section of the odd-page header. */
  oddHeader?: string
  /** Right section of the odd-page footer. */
  oddFooter?: string
  /** Left section of the even-page header. */
  evenHeader?: string
  /** Right section of the even-page footer. */
  evenFooter?: string
  /** Left section of the first-page header. */
  firstHeader?: string
  /** Right section of the first-page footer. */
  firstFooter?: string
  /** Align header/footer margins with page margins. */
  alignWithMargins?: boolean
  /** Use a different first-page header/footer. */
  differentFirst?: boolean
  /** Use different odd- and even-page headers/footers. */
  differentOddEven?: boolean
}

/**
 * Anchor descriptor for an embedded image.
 *
 * `anchor_type` is `"oneCell"` (image pinned to a single cell + offset) or
 * `"twoCell"` (image spans from top-left to bottom-right corners). For
 * `"oneCell"`, use `col`/`row`/`x`/`y`; for `"twoCell"`, `col2`/`row2`/`x2`/`y2`
 * describe the bottom-right corner.
 */
export interface ImageAnchor {
  anchorType: string
  col: number
  row: number
  x: number
  y: number
  col2: number
  row2: number
  x2: number
  y2: number
}

export interface ImageInfo {
  extension: string
  buffer: Array<number>
  positioning: string
  anchor: ImageAnchor
}

/** Page margins in inches (Excel `CT_PageMargins`). */
export interface PageMargins {
  left?: number
  right?: number
  top?: number
  bottom?: number
  header?: number
  footer?: number
}

/** Page setup / print descriptor for a worksheet (mirrors ExcelJS `ws.pageSetup`). */
export interface PageSetup {
  /** "portrait" or "landscape". */
  orientation?: string
  /** Paper size index (e.g. 9 = A4, 1 = Letter). */
  paperSize?: number
  /** Fit the sheet to fitToWidth × fitToHeight pages. */
  fitToPage?: boolean
  fitToWidth?: number
  fitToHeight?: number
  horizontalDpi?: number
  verticalDpi?: number
  blackAndWhite?: boolean
  drawingPrinted?: boolean
  /** "none" | "asDisplayed" | "atEnd". */
  cellComments?: string
  copies?: number
  /** Page margins in inches. */
  margins?: PageMargins
  /** Print area as an A1 range string (e.g. "A1:D10"). */
  printArea?: string
  /** Print titles as an A1 range string (e.g. "Sheet1!$A:$A"). */
  printTitles?: string
}

/**
 * Flat tagged union for cell values across the FFI boundary.
 *
 * Discriminant is `value_type`:
 * - `"Null"` — no value (default)
 * - `"Number"` — numeric value (field: `number`)
 * - `"String"` — text value (field: `string`)
 * - `"Boolean"` — boolean value (field: `boolean`)
 * - `"Formula"` — formula string (field: `formula`; preserved, not evaluated)
 * - `"Error"` — error value (field: `error_value`)
 *
 * # Write-only variants (v0.5.0)
 * `Hyperlink`, `RichText`, `Merge` are write-only: they can be set via JS and
 * will be written to the XLSX, but calamine does not expose them on the read
 * path so they appear as `Null` when read back (see spec §9.2.1 item 2).
 * A rich text run: a text fragment with optional font formatting.
 */
export interface RichTextRun {
  /** Text content for this run. */
  text: string
  /** Font formatting for this run (optional). */
  font?: Font
}

/**
 * Sheet protection flags. Each flag controls whether the user may perform
 * that action when the sheet is protected. A `None` value means the flag
 * was not in the file; absence of the element means the sheet is unprotected.
 */
export interface SheetProtection {
  locked?: boolean
  autoFilter?: boolean
  deleteColumns?: boolean
  deleteRows?: boolean
  formatCells?: boolean
  formatColumns?: boolean
  formatRows?: boolean
  insertColumns?: boolean
  insertHyperlinks?: boolean
  insertRows?: boolean
  pivotTables?: boolean
  selectLockedCells?: boolean
  selectUnlockedCells?: boolean
  sort?: boolean
  /** The password hash (salted SHA-1), if set. Not exposed to JS by excelrs. */
  passwordHash?: string
  /** The password salt, if set. Not exposed to JS by excelrs. */
  saltValue?: string
}

/** A single sheet view descriptor, mirroring a `<sheetView><pane>` pair. */
export interface SheetView {
  /** Pane state: "frozen", "split", or absent (`""`). */
  state?: string
  /** Horizontal split position (number of columns frozen/split). */
  xSplit?: number
  /** Vertical split position (number of rows frozen/split). */
  ySplit?: number
  /** The top-left visible cell in the bottom-right pane (e.g. "A1"). */
  topLeftCell?: string
  /** Active pane identifier: "bottomLeft", "bottomRight", "topLeft", "topRight". */
  activePane?: string
}

/**
 * Aggregate style object. Each sub-field is optional; `None` means
 * that aspect of formatting is left at the built-in "Normal" default.
 *
 * **Semantics: full-replace.** Assigning a new `Style` replaces the
 * existing style entirely. Use the spread idiom (spec §6.9) to preserve
 * specific fields.
 */
export interface Style {
  font?: Font
  fill?: Fill
  border?: Border
  alignment?: Alignment
  /**
   * Format code string, e.g. `"0.00%"`, `"$#,##0.00"`, `"yyyy-mm-dd"`.
   * `None` means no format (Normal). `Some("")` is rejected.
   */
  numFmt?: string
}

/** A single workbook view descriptor (`CT_WorkbookView`). */
export interface WorkbookView {
  xWindow?: number
  yWindow?: number
  windowWidth?: number
  windowHeight?: number
  activeTab?: number
  firstSheet?: number
  minimized?: boolean
  showHorizontalScroll?: boolean
  showVerticalScroll?: boolean
  tabRatio?: number
  visibility?: string
}

/** Options for `Worksheet.addTable`. */
export interface AddTableOptions {
  name: string
  displayName?: string
  /** A1 range covering header + data (+ optional totals), e.g. "A1:C4". */
  ref: string
  headerRow?: boolean
  totalsRow?: boolean
  columns: Array<TableColumn>
  /** Data rows as raw value arrays (ExcelJS-compatible: `[[v1, v2], ...]`). */
  rows: Array<Array<number | string | boolean | null>>
  style?: TableStyle
  /** Optional autoFilter range for the table part. Defaults to the table ref. */
  autoFilter?: string
  /** Whether to emit a table <autoFilter> element. Defaults to true. Set false to omit it. */
  autoFilterEnabled?: boolean
}

/** A worksheet table — returned by `getTable` / `getTables`. */
export interface Table {
  name: string
  displayName: string
  /** A1 range covering header + data (+ optional totals). */
  ref: string
  headerRow: boolean
  totalsRow: boolean
  columns: Array<TableColumn>
  rows: Array<TableRow>
  style?: TableStyle
  autofilterRef?: string
}

/** A single table column definition. */
export interface TableColumn {
  /** Column header text (written into the header-row cell). */
  name: string
  /** Totals-row label (e.g. "Total"). Emitted as `totalsRowLabel`. */
  totalsRowLabel?: string
  /** Totals-row function (e.g. "sum", "average"). Emitted as `totalsRowFunction`. */
  totalsRowFunction?: string
}

/** One row of table data values (data rows only; the header is derived from columns). */
export interface TableRow {
  values: Array<CellValue>
}

/** Table style descriptor (metadata only — never used to compute cell styles). */
export interface TableStyle {
  /** Named table style, e.g. "TableStyleMedium2" (ExcelJS `style.theme`). */
  theme?: string
  showFirstColumn?: boolean
  showLastColumn?: boolean
  showRowStripes?: boolean
  showColumnStripes?: boolean
}
