/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A single cell in a worksheet.
 *
 * Holds its address (e.g., "A1"), position (1-indexed row/col), value, formula,
 * and style reference. Cells are **value types** across the FFI boundary — see
 * the module-level doc for mutation semantics.
 */
export declare class Cell {
  constructor(address: string, row: number, col: number)
  get value(): CellValue
  /**
   * Accepts JS primitives via serde_json::Value auto-conversion (napi v3 serde-json feature).
   * Dispatches to the correct CellValue variant based on the JSON value type.
   */
  set value(val: any)
  get address(): string
  get row(): number
  get col(): number
  get formula(): string | null
  /** Returns the cell's style, or `None` if Normal (index 0). */
  get style(): Style | null
  /**
   * Set the cell's style from a JS object. Full-replace semantics
   * (spec §6.9): assigning a new style replaces the existing one.
   *
   * - `null | undefined | {}` → resets to Normal (None).
   * - Throws `ExcelrsError::InvalidStyle` on validation failure.
   */
  set style(val: any)
}

/**
 * A column definition in a worksheet.
 *
 * Mirrors the exceljs `Column` interface: header label, data-binding key,
 * width in characters, hidden state, and 1-indexed column number.
 *
 * `col_num` is optional in the JS object. If omitted (or 0), it is
 * auto-assigned sequentially in `Worksheet.setColumns` — the first column
 * gets col_num=1, the second gets col_num=2, etc.  For sparse definitions
 * (e.g. defining only column B), pass the `colNum` explicitly.
 */
export declare class Column {
  constructor(header: string, key: string, width: number)
  get header(): string
  set header(val: string)
  get key(): string
  set key(val: string)
  get width(): number
  set width(val: number)
  get hidden(): boolean
  set hidden(val: boolean)
  get style(): Style | null
  set style(val: any)
  get colNum(): number
}

/**
 * A row in a worksheet.
 *
 * Cells are stored in a `HashMap<u32, Cell>` keyed by 1-indexed column number.
 * The row number is 1-indexed. Accessing a cell by column creates an empty cell
 * if one doesn't exist — the returned Cell is a clone (see clone-on-read semantics
 * in `cell.rs`).
 */
export declare class Row {
  constructor(number: number)
  get number(): number
  get height(): number | null
  set height(val: number | undefined | null)
  get hidden(): boolean
  set hidden(val: boolean)
  /**
   * Get cell by 1-indexed column number. Creates an empty cell if none exists.
   * This is the Rust backing for `Row.getCell(col: number)`.
   */
  getCellByColNum(col: number): Cell
  /**
   * Get cell by column letter. Creates an empty cell if none exists.
   * This is the Rust backing for `Row.getCell(col: string)`.
   */
  getCellByColLetter(colLetter: string): Cell
}

/**
 * Top-level workbook document.
 *
 * Wraps `WorkbookInner` behind `Arc<Mutex<>>` so that the `WorkbookXlsx`
 * handle can mutate the workbook state via a shared reference.
 *
 * # Clone-on-read semantics
 * Like all napi-rs model types, accessed worksheets are cloned across the FFI
 * boundary.  Cloning the `Workbook` itself clones the `Arc` — all clones share
 * the same inner state.
 */
export declare class Workbook {
  constructor()
  /**
   * Add a new worksheet with the given name.
   * Returns the created Worksheet.
   */
  addWorksheet(name: string): Worksheet
  /**
   * Get a worksheet by name (string) or 1-indexed position (number).
   * Returns `None` if not found.
   */
  getWorksheet(nameOrIndex: any): Worksheet | null
  get worksheets(): Array<Worksheet>
  get worksheetCount(): number
  /** ISO-8601 timestamp of workbook creation. */
  get created(): string
  /** ISO-8601 timestamp of last modification. */
  get modified(): string
  /**
   * Returns a `WorkbookXlsx` handle for async XLSX I/O.
   *
   * The handle shares the same underlying `Arc<Mutex<WorkbookInner>>`,
   * so reads through `.xlsx.read(buf)` mutate this workbook's state.
   */
  get xlsx(): WorkbookXlsx
}

/**
 * Async XLSX read/write handle.
 *
 * Obtained via `Workbook.xlsx` getter.  Shares the same underlying
 * `Arc<Mutex<WorkbookInner>>` as the parent Workbook.
 */
export declare class WorkbookXlsx {
  /**
   * Read an .xlsx file from a JS `Buffer`.  Async.
   *
   * Parses the buffer with calamine, then replaces the workbook state
   * in-place.  All existing worksheets are discarded.
   */
  read(buffer: Buffer): Promise<void>
  /** Read an .xlsx file from disk.  Async. */
  readFile(path: string): Promise<void>
  /**
   * Write the workbook to an .xlsx buffer.  Async.
   *
   * Clones the workbook state briefly under the lock, then builds the
   * .xlsx archive outside the lock (calamine / zip I/O is expensive).
   */
  write(): Promise<Buffer>
  /** Write the workbook to an .xlsx file on disk.  Async. */
  writeFile(path: string): Promise<void>
}

/**
 * A single worksheet (sheet) in a workbook.
 *
 * Rows are stored behind `Arc<Mutex<>>` so that any clone of a Worksheet
 * shares the same row state.  This is what makes `wb.addWorksheet() → ws`
 * → `ws.addRow(...)` work across the napi-rs FFI boundary.
 */
export declare class Worksheet {
  constructor(name: string)
  get name(): string
  set name(val: string)
  get id(): number
  /** Number of rows with content (highest row index with data). */
  get rowCount(): number
  /** Number of columns with content (highest column index across all rows). */
  get columnCount(): number
  /**
   * Get cell by A1-style address string (e.g., "A1", "BC42").
   * Returns an empty cell if the address is valid but hasn't been populated.
   */
  getCellByAddress(address: string): Cell
  /**
   * Get cell by 1-indexed row and column numbers.
   * Returns an empty cell if the coordinates are valid but haven't been populated.
   */
  getCellByRc(row: number, col: number): Cell
  /** Get row by 1-indexed row number. Creates the row if it doesn't exist. */
  getRow(rowNumber: number): Row
  /** Add a row of cell values. Returns the created Row. */
  addRow(values: Array<any>): Row
  /**
   * Get a contiguous range of rows starting at `start` (1-indexed).
   * Returns up to `count` rows.
   */
  getRows(start: number, count: number): Array<Row>
  /** Remove a row by number. No-op if the row doesn't exist. */
  removeRow(rowNumber: number): void
  /** All rows with content, sorted by row number. */
  get rows(): Array<Row>
  get columns(): Array<Column>
  /**
   * Set the style of a cell at (row, col).  Bypasses clone-on-read:
   * the cell is mutated inside the locked row map.
   */
  setCellStyle(row: number, col: number, style: any): void
  /**
   * Replace the worksheet's column definitions.
   *
   * Accepts a JS array of column descriptor objects (header, key, width,
   * optional hidden, optional style). Parsed server-side via serde.
   * Each column's style is validated (matching `Cell.set_style` behavior).
   * Replace the worksheet's column definitions.
   *
   * Accepts a JS array of column descriptor objects (header, key, width,
   * optional `colNum`, optional hidden, optional style).  Parsed
   * server-side via serde.  Each column's style is validated (matching
   * `Cell.set_style` behavior).
   *
   * `colNum` auto-assignment: columns with `colNum == 0` get sequential
   * numbers starting from `max(existing col_nums) + 1` (or 1 if none
   * exist).  Duplicate `colNum` values across the same call are rejected.
   */
  setColumns(cols: any): void
}

/** Cell content alignment and text wrapping. */
export interface Alignment {
  /** Horizontal: `"left"` | `"center"` | `"right"` | `"fill"` | `"justify"`. */
  horizontal?: string
  /** Vertical: `"top"` | `"middle"` | `"bottom"`. */
  vertical?: string
  wrapText?: boolean
  indent?: number
}

/** All four cell-border sides. Each side is optional; `None` means no border. */
export interface Border {
  top?: BorderStyle
  right?: BorderStyle
  bottom?: BorderStyle
  left?: BorderStyle
}

/** Border line style and color for one side of a cell border. */
export interface BorderStyle {
  /**
   * Border style: `"thin"` | `"medium"` | `"thick"` | `"dashed"` |
   * `"dotted"` | `"double"`. `"none"` is rejected; use `None` for
   * the border side (e.g. `Border.top = None`) to express no border.
   */
  style: string
  /** Line color (ARGB hex). Default: black (`"FF000000"` in exceljs). */
  color?: string
}

/**
 * Flat tagged union for cell values across the FFI boundary.
 *
 * Discriminant is `value_type`:
 * - `"Null"` — no value (default)
 * - `"Number"` — numeric value (field: `number`)
 * - `"String"` — text value (field: `string`)
 * - `"Boolean"` — boolean value (field: `boolean`)
 * - `"Formula"` — formula string (field: `formula`; preserved, not evaluated)
 * - `"Error"` — error value (field: `error_value`)
 *
 * # Variants deferred from v0.1
 * `Hyperlink`, `RichText`, `SharedString`, and `Merge` are not included because
 * calamine does not expose them on the read path. They will be reintroduced in v0.2.
 */
export interface CellValue {
  /** Discriminant: "Null" | "Number" | "String" | "Boolean" | "Formula" | "Error" */
  valueType: string
  number?: number
  string?: string
  boolean?: boolean
  formula?: string
  errorValue?: string
}

/** Cell fill: kind, foreground, background, and pattern. */
export interface Fill {
  /**
   * Fill kind: `"none"` | `"solid"` | `"pattern"`.
   * `"gradient"` is rejected in v0.2.0 (see spec §9.2.1).
   */
  kind: string
  /** Foreground color (ARGB hex). Default: None. */
  foreground?: string
  /** Background color (ARGB hex). Default: None. */
  background?: string
  /** Pattern name (for `kind="pattern"`). Default: None. */
  pattern?: string
}

/** Font properties: name, size (points), weight, style, and color. */
export interface Font {
  /** Font name (e.g. "Calibri", "Arial"). Default: "Calibri". */
  name?: string
  /** Font size in points. Default: 11. Must be finite. */
  size?: number
  bold?: boolean
  italic?: boolean
  underline?: boolean
  /** ARGB hex (8 chars) or RGB hex (6 chars). Default: None. */
  color?: string
}

/**
 * Aggregate style object. Each sub-field is optional; `None` means
 * that aspect of formatting is left at the built-in "Normal" default.
 *
 * **Semantics: full-replace.** Assigning a new `Style` replaces the
 * existing style entirely. Use the spread idiom (spec §6.9) to preserve
 * specific fields.
 */
export interface Style {
  font?: Font
  fill?: Fill
  border?: Border
  alignment?: Alignment
  /**
   * Format code string, e.g. `"0.00%"`, `"$#,##0.00"`, `"yyyy-mm-dd"`.
   * `None` means no format (Normal). `Some("")` is rejected.
   */
  numFmt?: string
}
