/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A single cell in a worksheet.
 *
 * Holds its address (e.g., "A1"), position (1-indexed row/col), value, formula,
 * and style reference. Cells are **value types** across the FFI boundary — see
 * the module-level doc for mutation semantics.
 */
export declare class Cell {
  constructor(address: string, row: number, col: number)
  get value(): CellValue
  /**
   * Accepts JS primitives via serde_json::Value auto-conversion (napi v3 serde-json feature).
   * Dispatches to the correct CellValue variant based on the JSON value type.
   */
  set value(val: any)
  get address(): string
  get row(): number
  get col(): number
  get formula(): string | null
}

/**
 * A column definition in a worksheet.
 *
 * Mirrors the exceljs `Column` interface: header label, data-binding key,
 * width in characters, and hidden state.
 */
export declare class Column {
  constructor(header: string, key: string, width: number)
  get header(): string
  set header(val: string)
  get key(): string
  set key(val: string)
  get width(): number
  set width(val: number)
  get hidden(): boolean
  set hidden(val: boolean)
}

/**
 * A row in a worksheet.
 *
 * Cells are stored in a `HashMap<u32, Cell>` keyed by 1-indexed column number.
 * The row number is 1-indexed. Accessing a cell by column creates an empty cell
 * if one doesn't exist — the returned Cell is a clone (see clone-on-read semantics
 * in `cell.rs`).
 */
export declare class Row {
  constructor(number: number)
  get number(): number
  get height(): number | null
  set height(val: number | undefined | null)
  get hidden(): boolean
  set hidden(val: boolean)
  /**
   * Get cell by 1-indexed column number. Creates an empty cell if none exists.
   * This is the Rust backing for `Row.getCell(col: number)`.
   */
  getCellByColNum(col: number): Cell
  /**
   * Get cell by column letter. Creates an empty cell if none exists.
   * This is the Rust backing for `Row.getCell(col: string)`.
   */
  getCellByColLetter(colLetter: string): Cell
}

/**
 * Top-level workbook document.
 *
 * Wraps `WorkbookInner` behind `Arc<Mutex<>>` so that the `WorkbookXlsx`
 * handle can mutate the workbook state via a shared reference.
 *
 * # Clone-on-read semantics
 * Like all napi-rs model types, accessed worksheets are cloned across the FFI
 * boundary.  Cloning the `Workbook` itself clones the `Arc` — all clones share
 * the same inner state.
 */
export declare class Workbook {
  constructor()
  /**
   * Add a new worksheet with the given name.
   * Returns the created Worksheet.
   */
  addWorksheet(name: string): Worksheet
  /**
   * Get a worksheet by name (string) or 1-indexed position (number).
   * Returns `None` if not found.
   */
  getWorksheet(nameOrIndex: any): Worksheet | null
  get worksheets(): Array<Worksheet>
  get worksheetCount(): number
  /** ISO-8601 timestamp of workbook creation. */
  get created(): string
  /** ISO-8601 timestamp of last modification. */
  get modified(): string
  /**
   * Returns a `WorkbookXlsx` handle for async XLSX I/O.
   *
   * The handle shares the same underlying `Arc<Mutex<WorkbookInner>>`,
   * so reads through `.xlsx.read(buf)` mutate this workbook's state.
   */
  get xlsx(): WorkbookXlsx
}

/**
 * Async XLSX read/write handle.
 *
 * Obtained via `Workbook.xlsx` getter.  Shares the same underlying
 * `Arc<Mutex<WorkbookInner>>` as the parent Workbook.
 */
export declare class WorkbookXlsx {
  /**
   * Read an .xlsx file from a JS `Buffer`.  Async.
   *
   * Parses the buffer with calamine, then replaces the workbook state
   * in-place.  All existing worksheets are discarded.
   */
  read(buffer: Buffer): Promise<void>
  /** Read an .xlsx file from disk.  Async. */
  readFile(path: string): Promise<void>
  /**
   * Write the workbook to an .xlsx buffer.  Async.
   *
   * Clones the workbook state briefly under the lock, then builds the
   * .xlsx archive outside the lock (calamine / zip I/O is expensive).
   */
  write(): Promise<Buffer>
  /** Write the workbook to an .xlsx file on disk.  Async. */
  writeFile(path: string): Promise<void>
}

/**
 * A single worksheet (sheet) in a workbook.
 *
 * Rows are stored behind `Arc<Mutex<>>` so that any clone of a Worksheet
 * shares the same row state.  This is what makes `wb.addWorksheet() → ws`
 * → `ws.addRow(...)` work across the napi-rs FFI boundary.
 */
export declare class Worksheet {
  constructor(name: string)
  get name(): string
  set name(val: string)
  get id(): number
  /** Number of rows with content (highest row index with data). */
  get rowCount(): number
  /** Number of columns with content (highest column index across all rows). */
  get columnCount(): number
  /**
   * Get cell by A1-style address string (e.g., "A1", "BC42").
   * Returns an empty cell if the address is valid but hasn't been populated.
   */
  getCellByAddress(address: string): Cell
  /**
   * Get cell by 1-indexed row and column numbers.
   * Returns an empty cell if the coordinates are valid but haven't been populated.
   */
  getCellByRc(row: number, col: number): Cell
  /** Get row by 1-indexed row number. Creates the row if it doesn't exist. */
  getRow(rowNumber: number): Row
  /** Add a row of cell values. Returns the created Row. */
  addRow(values: Array<any>): Row
  /**
   * Get a contiguous range of rows starting at `start` (1-indexed).
   * Returns up to `count` rows.
   */
  getRows(start: number, count: number): Array<Row>
  /** Remove a row by number. No-op if the row doesn't exist. */
  removeRow(rowNumber: number): void
  /** All rows with content, sorted by row number. */
  get rows(): Array<Row>
  get columns(): Array<Column>
}

/**
 * Flat tagged union for cell values across the FFI boundary.
 *
 * Discriminant is `value_type`:
 * - `"Null"` — no value (default)
 * - `"Number"` — numeric value (field: `number`)
 * - `"String"` — text value (field: `string`)
 * - `"Boolean"` — boolean value (field: `boolean`)
 * - `"Formula"` — formula string (field: `formula`; preserved, not evaluated)
 * - `"Error"` — error value (field: `error_value`)
 *
 * # Variants deferred from v0.1
 * `Hyperlink`, `RichText`, `SharedString`, and `Merge` are not included because
 * calamine does not expose them on the read path. They will be reintroduced in v0.2.
 */
export interface CellValue {
  /** Discriminant: "Null" | "Number" | "String" | "Boolean" | "Formula" | "Error" */
  valueType: string
  number?: number
  string?: string
  boolean?: boolean
  formula?: string
  errorValue?: string
}
