#!/usr/bin/env node
// scripts/apply-glue.cjs
// Post-build hook for napi --pipe: re-injects ExcelJS-compat getCell overloads
// into the generated index.js / index.d.ts.
//
// Called by:  napi build --pipe "node scripts/apply-glue.cjs"
// Mechanism: napi passes the output file path as process.argv[2].

const fs = require('fs')
const path = require('path')

const JS_MARKER = '__EXCELJS_GETCELL_GLUE__'

const JS_GLUE = `
// __EXCELJS_GETCELL_GLUE__
// JS glue: ExcelJS-compat getCell overloads (delegate to Rust getCellBy* APIs)
nativeBinding.Worksheet.prototype.getCell = function (a, b) {
  return b === undefined ? this.getCellByAddress(a) : this.getCellByRc(a, b)
}
nativeBinding.Row.prototype.getCell = function (col) {
  return typeof col === 'number' ? this.getCellByColNum(col) : this.getCellByColLetter(col)
}
`

// Discriminated union form of CellValue so TS narrows on valueType without a cast.
// Replaces the flat `export interface CellValue { … }` block generated by napi.
const CELLVALUE_UNION_TYPE = `export type CellValue =
  | { valueType: "Null" }
  | { valueType: "Number"; number: number }
  | { valueType: "String"; string: string }
  | { valueType: "Boolean"; boolean: boolean }
  | { valueType: "Date"; dateSerial: number }
  | { valueType: "Formula"; formula: string }
  | { valueType: "Error"; errorValue: string }
  | { valueType: "Hyperlink"; hyperlink: string; hyperlinkText?: string }
  | { valueType: "RichText"; richText: Array<RichTextRun> }
  | { valueType: "Merge" };`

const DTS_MARKER = '__EXCELJS_GETCELL_GLUE__'

const DTS_GLUE = `
// __EXCELJS_GETCELL_GLUE__
// ExcelJS-compat getCell overloads (TypeScript declaration merging)
export interface Worksheet {
  /** Get cell by A1-style address string (JS glue → getCellByAddress). */
  getCell(address: string): Cell
  /** Get cell by 1-indexed row and column numbers (JS glue → getCellByRc). */
  getCell(row: number, col: number): Cell
}
export interface Row {
  /** Get cell by 1-indexed column number (JS glue → getCellByColNum). */
  getCell(col: number): Cell
  /** Get cell by column letter (JS glue → getCellByColLetter). */
  getCell(col: string): Cell
}

`

function processFile(filePath) {
  const basename = path.basename(filePath)

  // JS glue: ExcelJS-compat getCell overloads
  if (basename === 'index.js') {
    let content = fs.readFileSync(filePath, 'utf8')
    if (content.includes(JS_MARKER)) return false
    content = content.trimEnd() + '\n' + JS_GLUE + '\n'
    fs.writeFileSync(filePath, content)
    console.log(`[apply-glue] Patched ${filePath} (added Worksheet/Row getCell)`)
    return true
  }

  // DTS files: CellValue union transform + getCell overloads (index.d.ts only)
  // IMPORTANT: CellValue replacement is done BEFORE the DTS_MARKER early-return,
  // so a pre-existing index.d.ts (with DTS_MARKER from a prior build) still gets
  // the union transform on rebuilds.
  if (basename === 'native.d.ts' || basename === 'index.d.ts') {
    let content = fs.readFileSync(filePath, 'utf8')
    let modified = false

    // Replace flat CellValue interface with discriminated union (idempotent).
    // The generated interface spans multiple lines; regex anchored to the
    // start marker + lazy [^}]* match to the closing brace on its own line.
    if (content.includes('export interface CellValue {')) {
      content = content.replace(
        /export interface CellValue \{[^}]*\n\}/,
        CELLVALUE_UNION_TYPE
      )
      modified = true
    }

    // Add getCell overloads (only for index.d.ts)
    if (basename === 'index.d.ts') {
      if (content.includes(DTS_MARKER)) {
        // CellValue already handled above; write if we replaced it.
        if (modified) {
          fs.writeFileSync(filePath, content)
          console.log(`[apply-glue] Patched ${filePath} (CellValue union)`)
          return true
        }
        return false
      }
      content = content.trimEnd() + '\n' + DTS_GLUE + '\n'
      modified = true
    }

    if (modified) {
      fs.writeFileSync(filePath, content)
      console.log(`[apply-glue] Patched ${filePath}`)
      return true
    }
  }

  return false
}

// napi --pipe passes the output file path as process.argv[2]
const filePath = process.argv[2]
if (filePath) {
  processFile(filePath)
  // Also ensure index.d.ts gets getCell overloads when index.js is piped
  if (path.basename(filePath) === 'index.js') {
    const dtsPath = path.join(path.dirname(filePath), 'index.d.ts')
    if (fs.existsSync(dtsPath)) processFile(dtsPath)
  }
} else {
  // Fallback: patch index.js and index.d.ts in cwd
  for (const f of ['index.js', 'index.d.ts']) {
    if (fs.existsSync(f)) processFile(f)
  }
}