#!/usr/bin/env node
// scripts/apply-glue.cjs
// Post-build hook for napi --pipe: transforms the GENERATED type declarations
// (native.d.ts) — replacing the flat CellValue interface with a discriminated
// union, appending CellValueInput, refining the Cell value setter, and injecting
// the getCell overload declarations into the generated classes.
//
// It does NOT touch index.js or index.d.ts. Those are hand-maintained sources
// that the build never emits (napi is pointed at `native.js` / `native.d.ts` so
// it cannot clobber them), so the runtime getCell glue in index.js is maintained
// by hand. `scripts/verify-build-output.cjs` asserts both halves are present.
//
// Called by:  napi build --pipe "node scripts/apply-glue.cjs"
// Mechanism: napi passes the output file path as process.argv[2].

const fs = require('fs')
const path = require('path')

// Discriminated union form of CellValue so TS narrows on valueType without a cast.
// Replaces the flat `export interface CellValue { … }` block generated by napi.
const CELLVALUE_UNION_TYPE = `export type CellValue =
  | { valueType: "Null" }
  | { valueType: "Number"; number: number }
  | { valueType: "String"; string: string }
  | { valueType: "Boolean"; boolean: boolean }
  | { valueType: "Date"; dateSerial: number }
  | { valueType: "Formula"; formula: string; number?: number; string?: string; boolean?: boolean; errorValue?: string; dateSerial?: number }
  | { valueType: "Error"; errorValue: string }
  | { valueType: "Hyperlink"; hyperlink: string; hyperlinkText?: string }
  | { valueType: "RichText"; richText: Array<RichTextRun> }
  | { valueType: "Merge" };`

// Input form for the Cell.value setter: same variants but with an optional
// discriminant, so object-shaped values can be assigned with or without
// valueType. A union (not a flat interface) so excess-property checking rejects
// cross-variant field mixes like { valueType: "Number", string: "x" }.
const CELLVALUE_INPUT_TYPE = `export type CellValueInput =
  | { valueType?: "Null" }
  | { valueType?: "Number"; number: number }
  | { valueType?: "String"; string: string }
  | { valueType?: "Boolean"; boolean: boolean }
  | { valueType?: "Date"; dateSerial: number }
  | { valueType?: "Formula"; formula: string; number?: number; string?: string; boolean?: boolean; errorValue?: string; dateSerial?: number }
  | { valueType?: "Error"; errorValue: string }
  | { valueType?: "Hyperlink"; hyperlink: string; hyperlinkText?: string }
  | { valueType?: "RichText"; richText: Array<RichTextRun> }
  | { valueType?: "Merge" };`

// Class body refinements inlined into napi-generated declarations
// to avoid unsafe class + interface declaration merging.
const REFINED_CELL_VALUE_SETTER = `  /**
   * Accepts primitives, CellValueInput-like objects, or Date — dispatch by shape.
   */
  set value(val: CellValueInput | string | number | boolean | Date | null)`

const DEPRECATED_CELL_DATE_GETTER = `  /**
   * @deprecated Use \`cell.value\` instead (returns Date for Date cells).
   * Will be removed in v3.
   */
  get date(): Date | null`

const ROW_GETCELL_GLUE = `  /** Get cell by 1-indexed column number (JS glue → getCellByColNum). */
  getCell(col: number): Cell
  /** Get cell by column letter (JS glue → getCellByColLetter). */
  getCell(col: string): Cell`

const WORKSHEET_GETCELL_GLUE = `  /** Get cell by A1-style address string (JS glue → getCellByAddress). */
  getCell(address: string): Cell
  /** Get cell by 1-indexed row and column numbers (JS glue → getCellByRc). */
  getCell(row: number, col: number): Cell`

function processFile(filePath) {
  const basename = path.basename(filePath)

  // DTS files: CellValue union transform + getCell overload declarations.
  // Only `native.d.ts` is a build output; `index.d.ts` and `index.js` are
  // hand-maintained and are never emitted by the build, so they are not handled.
  if (basename === 'native.d.ts') {
    let content = fs.readFileSync(filePath, 'utf8')
    let modified = false

    // Replace flat CellValue interface with discriminated union (idempotent).
    // The generated interface spans multiple lines; regex anchored to the
    // start marker + lazy [^}]* match to the closing brace on its own line.
    if (content.includes('export interface CellValue {')) {
      content = content.replace(
        /export interface CellValue \{[^}]*\n\}/,
        CELLVALUE_UNION_TYPE
      )
      modified = true
    }

    // Append CellValueInput right after the union (idempotent).
    if (content.includes('export type CellValue =') && !content.includes('export type CellValueInput =')) {
      content = content.replace(
        /(export type CellValue =[^\n]*(?:\n[^\n]*)*?;\n)/,
        '$1' + '\n' + CELLVALUE_INPUT_TYPE + '\n'
      )
      modified = true
    }

    // --- Class body refinements ---
    // Inline into napi-generated class declarations instead of using
    // declaration merging (export interface + export declare class).

    // Cell: refined set value type (napi emits unknown)
    if (content.includes('  set value(val: unknown)')) {
      content = content.replace(
        /  \/\*\*\n   \* Accepts JS primitives and CellValue objects\.[\s\S]*?\n  set value\(val: unknown\)/,
        REFINED_CELL_VALUE_SETTER
      )
      modified = true
    }

    // Cell: add @deprecated to date getter
    const plainDateGetter = '  /** Returns a JS `Date` for Date-type cells, or `null` otherwise. */\n  get date(): Date | null'
    if (content.includes(plainDateGetter)) {
      content = content.replace(plainDateGetter, DEPRECATED_CELL_DATE_GETTER)
      modified = true
    }

    // Row: inject getCell overloads before closing }
    if (content.includes('getCellByColLetter(colLetter: string): Cell\n}')) {
      content = content.replace(
        /(getCellByColLetter\(colLetter: string\): Cell\n)\}/,
        '$1' + ROW_GETCELL_GLUE + '\n}'
      )
      modified = true
    }

    // Worksheet: inject getCell overloads before closing }
    if (content.includes('removeTable(name: string): boolean\n}')) {
      content = content.replace(
        /(removeTable\(name: string\): boolean\n)\}/,
        '$1' + WORKSHEET_GETCELL_GLUE + '\n}'
      )
      modified = true
    }

    if (modified) {
      fs.writeFileSync(filePath, content)
      console.log(`[apply-glue] Patched ${filePath}`)
      return true
    }
  }

  return false
}

// napi --pipe passes the output file path as process.argv[2]
const filePath = process.argv[2]
if (filePath) {
  processFile(filePath)
} else {
  // Fallback: patch the generated d.ts in cwd
  if (fs.existsSync('native.d.ts')) processFile('native.d.ts')
}